### ISSUE TITLE
Autocompletion includes too much

### ISSUE THREAD

**Issue by spaceotter** [senny/emacs-eclim#148]
When I complete with completing-read, the suggestions are like this:
getJSONArray(String name) : JSONArray - JSONObject
and that actually gets inserted into the file, when only getJSONArray should be inserted. The extra information is helpful, but is not a part of the actual symbol.

**Comment by Rishka** [comment]
I also have this issue, however I am not sure the bug is including the arguments. When using company mode with C# I get the same kind of completion, but the arguments fields are editable.

For example:

![ex1](https://cloud.githubusercontent.com/assets/7206343/7378303/7c2be6ba-edba-11e4-8b75-9dce7bc02d6a.png)
completion with arguments:
![ex2](https://cloud.githubusercontent.com/assets/7206343/7378304/7c3739b6-edba-11e4-84b1-62e8b31a0c6a.png)
editing arguments(tab to next)
![ex3](https://cloud.githubusercontent.com/assets/7206343/7378305/7c38f44a-edba-11e4-9ba0-1fc857397200.png)

**Comment by spaceotter** [comment]
For the record, I was using auto-complete mode. I switched over to company-mode awhile back and IIRC the problem went away.

**Comment by Rishka** [comment]
I was using company-mode when this happened to me.

Turning on yas-minor-mode gives the behavior in my comment. I believe that it should complete like that when yas-minor-mode is active and autocomplete without args when it is not.
