### ISSUE TITLE
Add Checkstyle *Feature*

### ISSUE THREAD

**Issue by gopar** [senny/emacs-eclim#231]
I saw on vim that you are able to [call checkstyle](https://github.com/ervandew/eclim/blob/e91dcb482d3024a233ce6a212e16ea8ad1209d50/org.eclim.jdt/java/org/eclim/plugin/jdt/command/src/CheckstyleCommand.java) on the current file. It would be nice to have this in emacs too. Not sure how much effort it would take to create this.

**Comment by kleewho** [comment]
Since it's per buffer you could take a look at flycheck. Although I can simply imagine situation when user is very confused by the information from flycheck and our own custom problems marks. Maybe... maybe it would be better first to add scope (workspace/file?) to problems command in `eclim` to be able to call it per buffer and then use flycheck for both.
